name: VRT with Backstop JS
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches: 
      - main

jobs:
  install_node:
    name: Run BackstopJS
    runs-on: ubuntu-latest
    steps:
      - name: Install Node 20
        uses: actions/setup-node@v1
        with:
          node-version: 20.9

      - name: Install Backstop
        run:  npm install --force -g backstopjs

    #   - name: Create reference screenshot from source site
    #     run: backstop reference

      - name: Run Backstop
        run: backstop test





