name: VRT with Backstop JS
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches: 
      - main

defaults:
 run:
  working-directory: ./

jobs:
  install_node:
    name: Run BackstopJS
    runs-on: ubuntu-latest
    steps:
      - name: Install Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.9

      - name: Install Backstop
        run:  npm install --force -g backstopjs

      - name: Create reference screenshot(s)
        run: ./node_modules/.bin/backstop reference

      - name: Run Backstop
        run: ./node_modules/.bin/backstop test





